import React,{useEffect,useState} from 'react'
import {supabase} from '../lib/supabase.client'
const CSS=`.ad{min-height:100vh;background:#F6F4EF;color:#1D1B16;font-family:'Instrument Sans',sans-serif}.ad *{box-sizing:border-box}.ad-wrap{max-width:700px;margin:0 auto;padding:52px 24px 90px}.ad h1{font:42px/1.05 'GFS Didot',Georgia,serif;margin:10px 0}.ad-lede{color:#6E6A5C;line-height:1.65}.ad-card{background:#fff;border:1px solid #E1DDD0;border-radius:12px;padding:20px;margin-top:14px}.ad-card h2{font:24px 'GFS Didot',serif;font-weight:400;margin:0}.ad-card p{font-size:13px;color:#6E6A5C;line-height:1.6}.ad-btn{border:1px solid #C9C3B2;background:#fff;border-radius:8px;padding:10px 14px;font-weight:600;cursor:pointer}.ad-btn.danger{border-color:#C2492B;color:#C2492B}.ad-btn:disabled{opacity:.5}.ad-msg{margin-top:12px;font-size:12.5px;color:#587947}.ad-back{color:#1A56A8;text-decoration:none;font-size:13px}.ad-confirm{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.ad-confirm input{flex:1;min-width:180px;border:1px solid #C9C3B2;border-radius:8px;padding:10px}.ad-email{font-size:12px;color:#98937F;margin-top:5px}.ad-loading{color:#6E6A5C;padding:50px 0}@media(max-width:520px){.ad-wrap{padding:36px 16px 75px}.ad h1{font-size:36px}.ad-card{padding:17px}.ad-confirm{flex-direction:column}.ad-btn,.ad-confirm input{width:100%}}`
export default function AccountData(){
 const[email,setEmail]=useState(''),[checked,setChecked]=useState(false),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[confirm,setConfirm]=useState('')
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setEmail(data.session?.user?.email||'');setChecked(true)})},[])
 const clearHistory=async()=>{if(!window.confirm('Clear all saved Peitho practice history? This cannot be undone.'))return;setBusy('history');setMessage('');const{error}=await supabase.rpc('clear_my_practice_history');setBusy('');setMessage(error?error.message:'Your saved practice history has been cleared.')}
 const deleteAccount=async()=>{if(confirm.trim().toUpperCase()!=='DELETE')return;setBusy('account');setMessage('');const{error}=await supabase.rpc('delete_my_peitho_account');if(error){setBusy('');setMessage(error.message);return}await supabase.auth.signOut();window.location.href='/'}
 return <main className="ad"><style>{CSS}</style><div className="ad-wrap"><a className="ad-back" href="/">← Back to Peitho</a>{!checked?<div className="ad-loading">Opening account controls…</div>:!email?<><h1>Account & data</h1><div className="ad-card"><p>Sign in to manage your Peitho account and saved practice data.</p><a href="/"><button className="ad-btn">Go to sign in</button></a></div></>:<><h1>Account & data</h1><p className="ad-lede">Your Peitho account should stay under your control. These actions affect your saved practice data; raw session audio is not stored in your Peitho account.</p><div className="ad-email">Signed in as {email}</div><section className="ad-card"><h2>Reset password</h2><p>Send yourself a secure password-reset link.</p><a href="/forgot-password"><button className="ad-btn">Reset password</button></a></section><section className="ad-card"><h2>Clear practice history</h2><p>Deletes your saved sessions and coaching analyses, resets your streak and removes your scores from the live leaderboard. Your account and speaking profile stay active.</p><button className="ad-btn danger" disabled={!!busy} onClick={clearHistory}>{busy==='history'?'Clearing…':'Clear practice history'}</button></section><section className="ad-card"><h2>Delete Peitho account</h2><p>Permanently deletes your account and its associated profile, saved sessions, analyses, streak and leaderboard record. This cannot be undone.</p><div className="ad-confirm"><input value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Type DELETE to confirm"/><button className="ad-btn danger" disabled={busy==='account'||confirm.trim().toUpperCase()!=='DELETE'} onClick={deleteAccount}>{busy==='account'?'Deleting…':'Delete account'}</button></div></section>{message&&<div className="ad-msg">{message}</div>}</>}</div></main>
}
