import React from 'react'

const CSS=`
.pf{background:#F0EDE5;border-top:1px solid #E1DDD0;color:#6E6A5C;font-family:'Instrument Sans',-apple-system,'Segoe UI',sans-serif}.pf *{box-sizing:border-box}.pf-wrap{width:min(1180px,calc(100% - 48px));margin:0 auto;padding:46px 0 24px}.pf-grid{display:grid;grid-template-columns:1.5fr .8fr .8fr;gap:50px;padding-bottom:36px}.pf-brand{display:flex;align-items:center;gap:10px;color:#1D1B16;text-decoration:none;width:max-content}.pf-brand img{width:35px;height:35px;border-radius:9px}.pf-brand span{font:400 28px 'GFS Didot',Georgia,serif}.pf-copy{font-size:13px;line-height:1.65;max-width:40ch;margin:15px 0 0}.pf-col h4{margin:2px 0 14px;font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:#98937F}.pf-col a{display:block;color:#6E6A5C;text-decoration:none;font-size:12.5px;margin:9px 0;width:max-content}.pf-col a:hover{color:#1A56A8}.pf-bottom{border-top:1px solid #DDD8CB;padding-top:20px;display:flex;align-items:center;justify-content:space-between;gap:16px;font-size:11.5px;color:#98937F}.pf-bottom a{color:#6E6A5C;text-decoration:none}.pf-bottom a:hover{color:#1A56A8}.pf-made{color:#6E6A5C}
@media(max-width:720px){.pf-wrap{width:min(100% - 30px,1180px);padding-top:34px}.pf-grid{grid-template-columns:1fr 1fr;gap:28px}.pf-grid>div:first-child{grid-column:1/-1}.pf-bottom{align-items:flex-start;flex-direction:column}.pf-copy{max-width:55ch}}
@media(max-width:440px){.pf-grid{grid-template-columns:1fr}.pf-grid>div:first-child{grid-column:auto}.pf-wrap{padding-bottom:76px}}
`

export default function CreatorSignature(){
 return <footer className="pf"><style>{CSS}</style><div className="pf-wrap"><div className="pf-grid"><div><a className="pf-brand" href="/"><img src="/favicon.svg" alt=""/><span>Peitho</span></a><p className="pf-copy">A speaking gym for people who want clearer ideas, cleaner delivery and feedback grounded in what they actually said.</p></div><div className="pf-col"><h4>Peitho</h4><a href="/">Practice</a><a href="/leaderboard">Leaderboard</a><a href="/history">My progress</a></div><div className="pf-col"><h4>More</h4><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="https://linkedin.com/in/22satnam" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="https://x.com/22satnamdev" target="_blank" rel="noopener noreferrer">X / Twitter</a><a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">Portfolio</a></div></div><div className="pf-bottom"><span>© {new Date().getFullYear()} Peitho · Speak so they listen.</span><span className="pf-made">Made with ❤️ by <a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">Satnam</a></span></div></div></footer>
}
