import React from 'react'

const CSS=`
.pf{background:#F0EDE5;border-top:1px solid #E1DDD0;color:#6E6A5C;font-family:'Instrument Sans',-apple-system,'Segoe UI',sans-serif}.pf *{box-sizing:border-box}.pf-wrap{width:min(1180px,calc(100% - 48px));margin:0 auto;padding:30px 0 18px}.pf-grid{display:grid;grid-template-columns:1.45fr .72fr .9fr;gap:36px;padding-bottom:22px}.pf-brand{display:flex;align-items:center;gap:10px;color:#1D1B16;text-decoration:none;width:max-content}.pf-brand img{width:35px;height:35px;border-radius:9px}.pf-brand span{font:400 28px 'GFS Didot',Georgia,serif}.pf-copy{font-size:12.5px;line-height:1.55;max-width:42ch;margin:10px 0 0}.pf-col h4{margin:2px 0 9px;font-size:9.5px;letter-spacing:.12em;text-transform:uppercase;color:#98937F}.pf-col a,.pf-col button{display:block;color:#6E6A5C;text-decoration:none;font:400 12px 'Instrument Sans',-apple-system,'Segoe UI',sans-serif;margin:5px 0;width:max-content}.pf-col button{border:0;background:none;padding:0;cursor:pointer}.pf-col a:hover,.pf-col button:hover{color:#1A56A8}.pf-bottom{border-top:1px solid #DDD8CB;padding-top:13px;display:flex;align-items:center;justify-content:space-between;gap:14px;font-size:10.5px;color:#98937F}.pf-bottom a{color:#6E6A5C;text-decoration:none}.pf-bottom a:hover{color:#1A56A8}.pf-made{color:#6E6A5C}
@media(max-width:720px){.pf-wrap{width:min(100% - 30px,1180px);padding:22px 0 18px}.pf-grid{grid-template-columns:1fr 1fr;gap:16px 20px;padding-bottom:16px}.pf-grid>div:first-child{grid-column:1/-1}.pf-brand img{width:30px;height:30px}.pf-brand span{font-size:24px}.pf-copy{max-width:58ch;font-size:11.5px;line-height:1.5;margin-top:7px}.pf-col h4{margin-bottom:6px}.pf-col a{font-size:11.5px;margin:4px 0}.pf-bottom{align-items:center;flex-direction:row;flex-wrap:wrap;padding-top:11px;font-size:10px}}
@media(max-width:440px){.pf-wrap{width:min(100% - 26px,1180px);padding:20px 0 64px}.pf-grid{grid-template-columns:1fr 1fr;gap:12px 14px}.pf-grid>div:first-child{grid-column:1/-1}.pf-copy{max-width:36ch}.pf-bottom{display:grid;grid-template-columns:1fr;gap:5px}.pf-made{font-size:10px}}
`

export default function CreatorSignature(){
 return <footer className="pf"><style>{CSS}</style><div className="pf-wrap"><div className="pf-grid"><div><a className="pf-brand" href="/"><img src="/favicon.svg" alt=""/><span>Peitho</span></a><p className="pf-copy">A speaking gym for people who want clearer ideas, cleaner delivery and feedback grounded in what they actually said.</p></div><div className="pf-col"><h4>Peitho</h4><a href="/">Practice</a><a href="/leaderboard">Leaderboard</a><a href="/history">My progress</a></div><div className="pf-col"><h4>More</h4><button type="button" onClick={()=>window.dispatchEvent(new Event('peitho:open-insights'))}>↗ Live insights</button><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="https://linkedin.com/in/22satnam" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="https://x.com/22satnamdev" target="_blank" rel="noopener noreferrer">X / Twitter</a><a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">Portfolio</a></div></div><div className="pf-bottom"><span>© {new Date().getFullYear()} Peitho · Speak so they listen.</span><span className="pf-made">Made with ❤️ by <a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">Satnam</a></span></div></div></footer>
}
