import React,{useCallback,useEffect,useMemo,useState} from 'react'
import { supabase } from '../lib/supabase.client'

const CSS=`
.lb{min-height:100vh;background:#F6F4EF;color:#1D1B16;font-family:'Instrument Sans',sans-serif}.lb *{box-sizing:border-box}.lb-wrap{max-width:900px;margin:0 auto;padding:48px 28px 80px}.lb-top{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:30px}.lb-kicker{font-size:11px;color:#1A56A8;text-transform:uppercase;letter-spacing:.12em;font-weight:600}.lb h1{font:400 45px/1.05 'GFS Didot',Georgia,serif;margin:8px 0}.lb-lede{color:#6E6A5C;font-size:14px;max-width:58ch}.lb-back{color:#1A56A8;text-decoration:none;font-size:13px;white-space:nowrap}.lb-card{background:#fff;border:1px solid #E1DDD0;border-radius:14px;overflow:hidden}.lb-row{display:grid;grid-template-columns:48px minmax(0,1fr) 100px 90px;align-items:center;gap:12px;padding:16px 20px;border-bottom:1px solid #EEEAE0}.lb-row:last-child{border-bottom:0}.lb-head{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#98937F;background:#FBFAF7;padding-top:11px;padding-bottom:11px}.lb-rank{font:400 23px 'GFS Didot',Georgia,serif;color:#98937F}.lb-rank.top{color:#A87C24}.lb-name b{font:500 14px 'Instrument Sans',sans-serif}.lb-name small{display:block;font-size:10.5px;color:#98937F;margin-top:2px}.lb-score{font-size:20px;font-weight:600;color:#1A56A8;text-align:right}.lb-sessions{text-align:right;color:#6E6A5C;font-size:12px}.lb-note{font-size:11.5px;line-height:1.55;color:#98937F;margin-top:14px}.lb-live{display:inline-flex;align-items:center;gap:6px;color:#587947;font-size:11px}.lb-live i{width:7px;height:7px;border-radius:50%;background:#587947;display:inline-block}.lb-empty{padding:28px;color:#6E6A5C}.lb-me{background:rgba(26,86,168,.055)}
@media(max-width:620px){.lb-wrap{padding:32px 16px 70px}.lb-top{align-items:flex-start;flex-direction:column}.lb h1{font-size:38px}.lb-row{grid-template-columns:34px minmax(0,1fr) 58px;padding:14px 13px;gap:8px}.lb-row .lb-sessions{display:none}.lb-head .lb-name{font-size:10px}.lb-score{font-size:17px}.lb-rank{font-size:20px}}
`

type RealRow={user_id:string;name:string;weekly_best:number|null;weekly_sessions:number|null;best:number|null;sessions:number|null}
type DemoRow={name:string;weekly_score:number;sessions:number;sort_order:number}

export default function Leaderboard(){
 const[real,setReal]=useState<RealRow[]>([]),[demo,setDemo]=useState<DemoRow[]>([]),[me,setMe]=useState(''),[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{const[{data:r},{data:d},{data:s}]=await Promise.all([
   supabase.from('leaderboard_scores').select('user_id,name,weekly_best,weekly_sessions,best,sessions').gt('sessions',0).order('weekly_best',{ascending:false}).limit(30),
   supabase.from('leaderboard_benchmarks').select('name,weekly_score,sessions,sort_order').order('sort_order').limit(10),
   supabase.auth.getSession(),
 ]);setReal((r||[]) as RealRow[]);setDemo((d||[]) as DemoRow[]);setMe(s.session?.user?.id||'');setLoading(false)},[])
 useEffect(()=>{load();const id=setInterval(load,15000);const focus=()=>load();window.addEventListener('focus',focus);return()=>{clearInterval(id);window.removeEventListener('focus',focus)}},[load])
 const rows=useMemo(()=>{const live=real.map(x=>({id:x.user_id,name:x.name||'Speaker',score:Number(x.weekly_best||x.best||0),sessions:Number(x.weekly_sessions||x.sessions||0),demo:false}));if(live.length>=10)return live.slice(0,20);const fill=demo.slice(0,Math.max(0,10-live.length)).map((x,i)=>({id:`demo-${i}`,name:x.name,score:Number(x.weekly_score),sessions:Number(x.sessions),demo:true}));return [...live,...fill].sort((a,b)=>b.score-a.score).slice(0,10)},[real,demo])
 return <main className="lb"><style>{CSS}</style><div className="lb-wrap"><div className="lb-top"><div><div className="lb-kicker">This week</div><h1>Peitho leaderboard</h1><p className="lb-lede">A little friendly pressure. Your best session this week sets the score; practice keeps the board moving.</p><span className="lb-live"><i/> refreshes automatically</span></div><a className="lb-back" href="/">← Back to practice</a></div>{loading?<div className="lb-card lb-empty">Warming up the board…</div>:<div className="lb-card"><div className="lb-row lb-head"><span>#</span><span className="lb-name">Speaker</span><span className="lb-score">Score</span><span className="lb-sessions">Sessions</span></div>{rows.map((x,i)=><div className={'lb-row '+(x.id===me?'lb-me':'')} key={x.id}><span className={'lb-rank '+(i<3?'top':'')}>{i+1}</span><span className="lb-name"><b>{x.name}{x.id===me?' · You':''}</b><small>{x.demo?'Peitho practice benchmark':'Community speaker'}</small></span><span className="lb-score">{Math.round(x.score)}</span><span className="lb-sessions">{x.sessions} this week</span></div>)}</div>}<p className="lb-note">Practice benchmarks keep the board useful while the community is new. They automatically leave the board as more real speakers join.</p></div></main>
}
