import React from 'react'

const LAST_UPDATED = '18 September 2026'

const styles = `
@import url('https://fonts.googleapis.com/css2?family=GFS+Didot&family=Instrument+Sans:wght@400;500;600&display=swap');
.legal{min-height:100vh;background:#F6F4EF;color:#1D1B16;font-family:'Instrument Sans',-apple-system,'Segoe UI',sans-serif}.legal *{box-sizing:border-box}.legal-wrap{max-width:840px;margin:0 auto;padding:0 28px 72px}.legal-head{height:82px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #E1DDD0}.legal-brand{font:400 30px 'GFS Didot',Georgia,serif;color:#1D1B16;text-decoration:none}.legal-back{font-size:13px;color:#1A56A8;text-decoration:none}.legal-main{padding-top:62px}.legal-kicker{font-size:12px;text-transform:uppercase;letter-spacing:.12em;color:#1A56A8;font-weight:600}.legal h1{font:400 clamp(42px,7vw,64px)/1.05 'GFS Didot',Georgia,serif;margin:12px 0 12px}.legal-updated{color:#98937F;font-size:13px;margin-bottom:38px}.legal-intro{font-size:17px;line-height:1.75;color:#5F5B4F;border-bottom:1px solid #E1DDD0;padding-bottom:30px;margin-bottom:32px}.legal-section{margin:30px 0}.legal h2{font:400 27px/1.2 'GFS Didot',Georgia,serif;margin:0 0 10px}.legal p,.legal li{font-size:14px;line-height:1.75;color:#5F5B4F}.legal ul{padding-left:20px}.legal a{color:#1A56A8}.legal-note{background:#fff;border:1px solid #E1DDD0;border-radius:12px;padding:17px 19px}.legal-footer{border-top:1px solid #E1DDD0;margin-top:48px;padding-top:22px;font-size:12.5px;color:#98937F;display:flex;gap:12px;flex-wrap:wrap}.legal-footer a{color:#6E6A5C;text-decoration:none}.legal-footer a:hover{text-decoration:underline}
@media(max-width:600px){.legal-wrap{padding:0 18px 46px}.legal-head{height:68px}.legal-main{padding-top:38px}.legal h1{font-size:44px}.legal-intro{font-size:15px}.legal h2{font-size:24px}}
`

function Footer(){return <div className="legal-footer"><span>Made with ❤️ by Satnam</span><span>·</span><a href="https://linkedin.com/in/22satnam" target="_blank" rel="noopener noreferrer">LinkedIn</a><span>·</span><a href="https://x.com/22satnamdev" target="_blank" rel="noopener noreferrer">X</a><span>·</span><a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">Portfolio</a></div>}

export function PrivacyPage(){return <div className="legal"><style>{styles}</style><div className="legal-wrap"><header className="legal-head"><a className="legal-brand" href="/">Peitho</a><a className="legal-back" href="/">Back to Peitho</a></header><main className="legal-main"><div className="legal-kicker">Your data, in plain language</div><h1>Privacy Policy</h1><div className="legal-updated">Last updated {LAST_UPDATED}</div><p className="legal-intro">Peitho is an AI speaking coach built by Satnam Singh. This policy explains what information Peitho handles when you create an account and complete a speaking practice session, why it is used, and which service providers help process it.</p>
<section className="legal-section"><h2>1. Information you provide</h2><p>When you create a Peitho account, we may collect your name, email address, speaking goal and self-reported English level. If you use Google sign-in, Google and Supabase provide the account identity information needed to sign you in. Password authentication is handled by Supabase Auth; Peitho does not store your password in its application database.</p></section>
<section className="legal-section"><h2>2. Speaking-session data</h2><p>When you choose to start a practice session, Peitho accesses your microphone. During the session, short audio windows may be sent for live transcription. When you end the session, the recording is processed to create the final transcript, speaking metrics and coaching feedback.</p><ul><li><strong>Groq</strong> processes audio for speech-to-text transcription, including the live transcript and final transcript.</li><li><strong>Google Gemini</strong> may process the session audio, transcript and derived metrics to provide delivery and speaking feedback.</li><li><strong>Vercel</strong> hosts Peitho and runs the server-side application that coordinates these requests.</li></ul></section>
<section className="legal-section"><h2>3. What Peitho stores</h2><p>Supabase stores account and speaking-profile information such as your email, name, speaking goal and level. Peitho's database is configured with row-level access controls so authenticated users can access only data permitted to their account.</p><p>Peitho currently does not intentionally store the raw microphone recording in its application database after analysis. Audio sent to Gemini is uploaded temporarily for analysis and Peitho makes a best-effort request to delete that temporary Gemini file after the analysis finishes. Service providers may process or retain data according to their own service terms and policies.</p></section>
<section className="legal-section"><h2>4. Why we use this information</h2><p>We use the information above to authenticate your account, personalize practice, transcribe speech, calculate speaking metrics such as pace and filler frequency, generate coaching feedback, operate and secure the service, and improve the reliability of the Peitho experience.</p></section>
<section className="legal-section"><h2>5. AI-generated feedback</h2><p>Transcripts and coaching are produced with automated systems and can be wrong. Live captions in particular are a fast preview and may differ from the final full-session transcript. Peitho's feedback is for speaking practice and should not be treated as a professional assessment of a person's intelligence, health, identity or capabilities.</p></section>
<section className="legal-section"><h2>6. Sharing and sale of data</h2><p>Peitho does not sell your personal information. Data is shared with service providers only as needed to provide authentication, hosting, transcription and AI analysis, or where disclosure is required by law.</p></section>
<section className="legal-section"><h2>7. Your choices</h2><p>You control when microphone recording starts and can deny or revoke browser microphone permission. You may sign out at any time. If you want to ask about, correct or request deletion of account information, contact the creator using the portfolio link below. Some information may need to be retained where required for security, legal obligations or legitimate operational records.</p></section>
<section className="legal-section"><h2>8. Security</h2><p>Peitho uses Supabase authentication and database row-level security, keeps Groq and Gemini API keys on the server, and uses HTTPS in production. No internet service can guarantee absolute security, so Peitho should not be used to record confidential, regulated or highly sensitive information.</p></section>
<section className="legal-section"><h2>9. Changes</h2><p>This policy may be updated as Peitho adds features such as saved session history or changes service providers. The date at the top will be updated when material changes are made.</p></section>
<div className="legal-note"><strong>Contact</strong><p>Peitho is built by Satnam Singh. For privacy questions or data requests, use the contact details available at <a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">satnamsingh.in</a>.</p></div></main><Footer/></div></div>}

export function TermsPage(){return <div className="legal"><style>{styles}</style><div className="legal-wrap"><header className="legal-head"><a className="legal-brand" href="/">Peitho</a><a className="legal-back" href="/">Back to Peitho</a></header><main className="legal-main"><div className="legal-kicker">Using Peitho</div><h1>Terms of Use</h1><div className="legal-updated">Last updated {LAST_UPDATED}</div><p className="legal-intro">These terms apply when you use Peitho. Peitho is an evolving speaking-practice product, so the aim here is to set clear expectations rather than bury the service in legal language.</p>
<section className="legal-section"><h2>1. The service</h2><p>Peitho lets you record speaking-practice sessions and receive transcripts, metrics and AI-generated coaching. Features, limits, models and availability may change as the product develops.</p></section>
<section className="legal-section"><h2>2. Your account</h2><p>You are responsible for information submitted through your account and for keeping your login credentials secure. Do not use another person's account without permission. If you believe your account has been compromised, stop using it and contact Peitho.</p></section>
<section className="legal-section"><h2>3. Responsible use</h2><p>Do not use Peitho to break the law, abuse or harass others, attempt to compromise the service, bypass usage limits, automate excessive requests, or upload content you do not have permission to process. Do not deliberately submit highly sensitive or regulated information in recordings.</p></section>
<section className="legal-section"><h2>4. Your content</h2><p>You retain your rights in the speech and other content you submit. You give Peitho permission to process that content only as reasonably necessary to operate the service, including transcription, analysis, security and delivery of your feedback through the service providers described in the Privacy Policy.</p></section>
<section className="legal-section"><h2>5. AI limitations</h2><p>Speech recognition and AI feedback can be inaccurate, incomplete or inconsistent. Peitho is a practice and coaching tool, not a guaranteed measure of language proficiency, employability, intelligence or professional competence. Important decisions should not be based solely on a Peitho score or AI-generated recommendation.</p></section>
<section className="legal-section"><h2>6. Availability</h2><p>Peitho may experience interruptions caused by hosting, transcription or AI providers. Features may be limited, changed or discontinued. Where possible, Peitho may use fallback providers so a practice session can still return useful feedback.</p></section>
<section className="legal-section"><h2>7. No warranties</h2><p>Peitho is provided on an "as is" and "as available" basis to the extent permitted by applicable law. There is no promise that every transcript, score or suggestion will be error-free or that the service will always be available.</p></section>
<section className="legal-section"><h2>8. Liability</h2><p>To the extent permitted by applicable law, Peitho and its creator are not responsible for indirect or consequential losses arising from reliance on AI-generated feedback or interruptions in the service. Nothing in these terms excludes rights or liability that cannot legally be excluded.</p></section>
<section className="legal-section"><h2>9. Changes and access</h2><p>These terms may change as Peitho evolves. Access may be limited or suspended where necessary to protect users, the service, provider quotas or security.</p></section>
<section className="legal-section"><h2>10. Privacy</h2><p>How Peitho handles account, microphone, transcript and AI-processing data is described in the <a href="/privacy">Privacy Policy</a>.</p></section>
<div className="legal-note"><strong>Questions?</strong><p>Peitho is built by Satnam Singh. Contact information is available at <a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">satnamsingh.in</a>.</p></div></main><Footer/></div></div>}
