import React from 'react'
const LAST_UPDATED='18 September 2026'
const styles=`@import url('https://fonts.googleapis.com/css2?family=GFS+Didot&family=Instrument+Sans:wght@400;500;600&display=swap');.legal{min-height:100vh;background:#F6F4EF;color:#1D1B16;font-family:'Instrument Sans',sans-serif}.legal *{box-sizing:border-box}.legal-wrap{max-width:840px;margin:0 auto;padding:0 28px 72px}.legal-head{height:82px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #E1DDD0}.legal-brand{font:30px 'GFS Didot',serif;color:#1D1B16;text-decoration:none}.legal-back{font-size:13px;color:#1A56A8;text-decoration:none}.legal-main{padding-top:62px}.legal-kicker{font-size:12px;text-transform:uppercase;letter-spacing:.12em;color:#1A56A8;font-weight:600}.legal h1{font:clamp(42px,7vw,64px)/1.05 'GFS Didot',serif;margin:12px 0}.legal-updated{color:#98937F;font-size:13px;margin-bottom:38px}.legal-intro{font-size:17px;line-height:1.75;color:#5F5B4F;border-bottom:1px solid #E1DDD0;padding-bottom:30px;margin-bottom:32px}.legal-section{margin:30px 0}.legal h2{font:27px/1.2 'GFS Didot',serif;margin:0 0 10px}.legal p,.legal li{font-size:14px;line-height:1.75;color:#5F5B4F}.legal ul{padding-left:20px}.legal a{color:#1A56A8}.legal-note{background:#fff;border:1px solid #E1DDD0;border-radius:12px;padding:17px 19px}.legal-footer{border-top:1px solid #E1DDD0;margin-top:48px;padding-top:22px;font-size:12.5px;color:#98937F;display:flex;gap:12px;flex-wrap:wrap}.legal-footer a{color:#6E6A5C;text-decoration:none}@media(max-width:600px){.legal-wrap{padding:0 18px 46px}.legal-head{height:68px}.legal-main{padding-top:38px}.legal h1{font-size:44px}.legal-intro{font-size:15px}.legal h2{font-size:24px}}`
function Footer(){return <div className="legal-footer"><span>Made with ❤️ by Satnam</span><span>·</span><a href="/history">My progress</a><span>·</span><a href="/privacy">Privacy</a><span>·</span><a href="/terms">Terms</a><span>·</span><a href="https://linkedin.com/in/22satnam" target="_blank" rel="noopener noreferrer">LinkedIn</a><span>·</span><a href="https://x.com/22satnamdev" target="_blank" rel="noopener noreferrer">X</a><span>·</span><a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">Portfolio</a></div>}
const Shell=({kind,title,children}:{kind:string;title:string;children:React.ReactNode})=><div className="legal"><style>{styles}</style><div className="legal-wrap"><header className="legal-head"><a className="legal-brand" href="/">Peitho</a><a className="legal-back" href="/">Back to Peitho</a></header><main className="legal-main"><div className="legal-kicker">{kind}</div><h1>{title}</h1><div className="legal-updated">Last updated {LAST_UPDATED}</div>{children}</main><Footer/></div></div>

export function PrivacyPage(){return <Shell kind="Your data, in plain language" title="Privacy Policy"><p className="legal-intro">Peitho is an AI speaking coach built by Satnam Singh. This policy explains what information Peitho handles when you create an account and complete speaking practice, why it is used, what is saved to your account, and which providers help process it.</p>
<section className="legal-section"><h2>1. Account information</h2><p>Peitho may store your name, email address, speaking goal and self-reported English level. Google sign-in provides the identity information needed to authenticate you. Password authentication is handled by Supabase Auth; Peitho does not store your plaintext password.</p></section>
<section className="legal-section"><h2>2. Microphone and AI processing</h2><p>Microphone access begins only after you start a practice session. Short audio windows may be processed for live captions. When you end the session, the full recording is processed to create the final transcript, metrics and coaching.</p><ul><li><strong>Groq</strong> processes audio for live and final speech-to-text transcription.</li><li><strong>Google Gemini</strong> may process session audio, transcript and derived metrics for delivery and speaking feedback.</li><li><strong>Vercel</strong> hosts the application and server-side API.</li><li><strong>Supabase</strong> provides authentication and stores account and saved-session data.</li></ul></section>
<section className="legal-section"><h2>3. Saved sessions and progress</h2><p>After a successful analysis, Peitho stores the session topic, duration, final transcript, speaking metrics such as pace, fillers and pauses, category scores, and the generated coaching analysis in Supabase. This enables <strong>My progress</strong>, recent-session history and practice streaks. Row-level security is enabled so signed-in users can access only data allowed for their account.</p><p>Peitho does <strong>not intentionally store the raw microphone recording</strong> in its application database after analysis. Audio sent to Gemini is uploaded temporarily for analysis and Peitho makes a best-effort request to delete that temporary Gemini file afterward. Third-party providers may process or retain data according to their own service terms and policies.</p></section>
<section className="legal-section"><h2>4. Why Peitho uses data</h2><p>Data is used to authenticate accounts, personalize practice, produce live and final transcripts, calculate speaking metrics, generate coaching, save progress and streaks, secure the AI endpoints, enforce per-user usage limits, and operate the service.</p></section>
<section className="legal-section"><h2>5. AI limitations</h2><p>Speech recognition and AI coaching can be inaccurate. Live captions are a fast preview and can differ from the final full-session transcript. Scores are coaching signals, not formal language-test grades or assessments of intelligence, identity, health, employability or professional competence.</p></section>
<section className="legal-section"><h2>6. Sharing and sale</h2><p>Peitho does not sell personal information. Information is shared with service providers only as needed for authentication, hosting, transcription, AI analysis and operation of the service, or where disclosure is legally required.</p></section>
<section className="legal-section"><h2>7. Security and abuse prevention</h2><p>Peitho uses HTTPS, Supabase authentication and row-level security, keeps Groq and Gemini credentials server-side, requires signed-in API requests, and applies per-user limits to AI requests. No internet service can guarantee absolute security; do not record confidential, regulated or highly sensitive information.</p></section>
<section className="legal-section"><h2>8. Your choices and data requests</h2><p>You control microphone permission and may sign out at any time. You may request information about, correction of, or deletion of your Peitho account data by contacting the creator through the portfolio below. Some data may need to be retained where required for security, legal obligations or legitimate operational records.</p></section>
<section className="legal-section"><h2>9. Changes</h2><p>This policy may change as Peitho's features or service providers change. The date above will be updated for material changes.</p></section>
<div className="legal-note"><strong>Contact</strong><p>Peitho is built by Satnam Singh. For privacy questions or data requests, use the contact information at <a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">satnamsingh.in</a>.</p></div></Shell>}

export function TermsPage(){return <Shell kind="Using Peitho" title="Terms of Use"><p className="legal-intro">These terms apply when you use Peitho, an evolving AI speaking-practice product.</p>
<section className="legal-section"><h2>1. The service</h2><p>Peitho lets you record speaking practice and receive transcripts, metrics, saved progress and AI-generated coaching. Features, models, limits and availability may change.</p></section>
<section className="legal-section"><h2>2. Your account</h2><p>You are responsible for information submitted through your account and for keeping login credentials secure. Do not use another person's account without permission.</p></section>
<section className="legal-section"><h2>3. Responsible use</h2><p>Do not use Peitho to break the law, abuse others, compromise the service, bypass authentication or usage limits, automate excessive requests, or submit content you do not have permission to process.</p></section>
<section className="legal-section"><h2>4. Your content</h2><p>You retain your rights in speech and other content you submit. You permit Peitho to process and store it as reasonably necessary to provide transcription, analysis, saved progress, security and feedback as described in the Privacy Policy.</p></section>
<section className="legal-section"><h2>5. AI limitations</h2><p>Speech recognition and AI feedback can be inaccurate, incomplete or inconsistent. Peitho is a coaching tool, not a guaranteed measure of proficiency, intelligence, employability or professional competence.</p></section>
<section className="legal-section"><h2>6. Availability and limits</h2><p>Peitho may experience provider interruptions and may use fallback models. Per-user usage limits may be enforced to protect service availability and provider quotas.</p></section>
<section className="legal-section"><h2>7. No warranties and liability</h2><p>Peitho is provided on an "as is" and "as available" basis to the extent permitted by law. To the extent permitted by law, Peitho and its creator are not responsible for indirect or consequential losses from relying on AI feedback or service interruptions. Nothing here excludes rights or liability that cannot legally be excluded.</p></section>
<section className="legal-section"><h2>8. Changes and privacy</h2><p>These terms may change as Peitho evolves. How account, microphone, transcript and saved-session data is handled is described in the <a href="/privacy">Privacy Policy</a>.</p></section>
<div className="legal-note"><strong>Questions?</strong><p>Peitho is built by Satnam Singh. Contact information is available at <a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">satnamsingh.in</a>.</p></div></Shell>}
