import React from 'react'
import PublicNav from './PublicNav'
import CreatorSignature from './CreatorSignature'

const CSS=`
@import url('https://fonts.googleapis.com/css2?family=GFS+Didot&family=Instrument+Sans:ital,wght@0,400;0,500;0,600;1,400&display=swap');
.ml{--paper:#F6F4EF;--panel:#fff;--wash:#EFECE3;--line:#E1DDD0;--line2:#C9C3B2;--ink:#1D1B16;--dim:#6E6A5C;--faint:#98937F;--aegean:#1A56A8;--aegean-deep:#123E7C;--aegean-soft:rgba(26,86,168,.09);--gold:#A87C24;--clay:#C2492B;--laurel:#587947;--didot:'GFS Didot',Georgia,serif;--sans:'Instrument Sans',-apple-system,'Segoe UI',sans-serif;background:var(--paper);color:var(--ink);font-family:var(--sans);min-height:100vh;background-image:linear-gradient(rgba(29,27,22,.033) 1px,transparent 1px),linear-gradient(90deg,rgba(29,27,22,.033) 1px,transparent 1px);background-size:88px 88px}
.ml *{box-sizing:border-box}.ml-wrap{width:min(1180px,calc(100% - 48px));margin:0 auto}.ml-hero{min-height:690px;display:grid;grid-template-columns:minmax(0,1.15fr) minmax(360px,.85fr);align-items:center;gap:60px;padding:70px 0 84px}.ml-kicker{font-size:11px;text-transform:uppercase;letter-spacing:.14em;color:var(--aegean);font-weight:600}.ml h1{font:400 clamp(60px,7vw,102px)/.94 var(--didot);letter-spacing:-.045em;margin:17px 0 26px;max-width:10ch}.ml h1 em{font-weight:400;color:var(--clay);font-style:italic}.ml-lede{font-size:18px;line-height:1.72;color:var(--dim);max-width:59ch;margin:0}.ml-actions{display:flex;align-items:center;gap:12px;margin-top:34px}.ml-primary,.ml-secondary{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:0 18px;border-radius:10px;text-decoration:none;font-weight:600;font-size:13px}.ml-primary{background:var(--aegean);color:#fff;border:1px solid var(--aegean)}.ml-primary:hover{background:var(--aegean-deep)}.ml-secondary{color:var(--dim);border:1px solid var(--line2);background:rgba(255,255,255,.45)}.ml-secondary:hover{background:#fff;color:var(--aegean)}
.ml-preview{position:relative;min-height:510px;display:grid;place-items:center}.ml-orbit{position:absolute;width:430px;height:430px;border:1px solid rgba(26,86,168,.12);border-radius:50%}.ml-orbit:before,.ml-orbit:after{content:'';position:absolute;border:1px solid rgba(194,73,43,.09);border-radius:50%}.ml-orbit:before{inset:44px}.ml-orbit:after{inset:105px}.ml-card{position:relative;width:min(430px,100%);background:rgba(255,255,255,.93);border:1px solid var(--line);border-radius:20px;box-shadow:0 28px 70px rgba(29,27,22,.10);overflow:hidden}.ml-cardtop{padding:19px 20px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:14px}.ml-cardtitle{font:400 20px var(--didot)}.ml-live{font-size:10px;text-transform:uppercase;letter-spacing:.09em;color:var(--laurel);background:rgba(88,121,71,.09);padding:6px 8px;border-radius:999px}.ml-wave{height:108px;padding:22px 20px 14px;display:flex;gap:5px;align-items:center}.ml-wave i{display:block;width:4px;border-radius:999px;background:var(--aegean);opacity:.82}.ml-wave i:nth-child(3n){background:var(--clay)}.ml-caption{padding:0 20px 18px;color:var(--dim);font:400 19px/1.55 var(--didot);font-style:italic}.ml-caption mark{background:rgba(194,73,43,.1);color:var(--clay);padding:0 3px}.ml-stats{border-top:1px solid var(--line);display:grid;grid-template-columns:repeat(3,1fr)}.ml-stat{padding:15px 14px;text-align:center;border-right:1px solid var(--line)}.ml-stat:last-child{border-right:0}.ml-stat b{display:block;font-size:20px}.ml-stat span{display:block;font-size:10px;color:var(--faint);margin-top:3px}.ml-float{position:absolute;background:#fff;border:1px solid var(--line);border-radius:12px;box-shadow:0 18px 42px rgba(29,27,22,.08);padding:12px 14px}.ml-float.one{top:38px;right:-18px}.ml-float.two{bottom:48px;left:-34px}.ml-float b{display:block;font-size:18px;color:var(--aegean)}.ml-float span{display:block;font-size:10px;color:var(--faint);margin-top:3px}
.ml-band{border-top:1px solid rgba(225,221,208,.9);border-bottom:1px solid rgba(225,221,208,.9);background:rgba(246,244,239,.82);backdrop-filter:blur(8px)}.ml-section{padding:100px 0}.ml-sectionhead{display:grid;grid-template-columns:.8fr 1.2fr;gap:50px;margin-bottom:42px}.ml-eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.14em;color:var(--aegean);font-weight:600}.ml-section h2{font:400 clamp(42px,5vw,66px)/1 var(--didot);letter-spacing:-.03em;margin:11px 0 0;max-width:12ch}.ml-sectionhead p{font-size:16px;line-height:1.75;color:var(--dim);max-width:58ch;margin:28px 0 0}.ml-grid3{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid var(--line);border-radius:22px;overflow:hidden;background:rgba(255,255,255,.55)}.ml-feature{padding:32px 30px;min-height:220px;border-right:1px solid var(--line)}.ml-feature:last-child{border-right:0}.ml-icon{width:40px;height:40px;border-radius:10px;background:var(--aegean-soft);display:grid;place-items:center;color:var(--aegean);font-weight:700}.ml-feature h3{font:400 24px var(--didot);margin:26px 0 9px}.ml-feature p{font-size:13.5px;line-height:1.65;color:var(--dim);margin:0}.ml-report{display:grid;grid-template-columns:.9fr 1.1fr;gap:54px;align-items:center}.ml-reportcard{background:#fff;border:1px solid var(--line);border-radius:18px;overflow:hidden;box-shadow:0 24px 64px rgba(29,27,22,.065)}.ml-reporthead{padding:20px 22px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:end}.ml-reporthead span{font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:var(--faint)}.ml-reporthead b{font:400 34px var(--didot);color:var(--aegean)}.ml-row{display:grid;grid-template-columns:140px 66px 1fr;gap:16px;padding:15px 22px;border-bottom:1px solid var(--line);align-items:center}.ml-row:last-child{border-bottom:0}.ml-row strong{font-size:13px}.ml-row b{font-size:15px}.ml-row p{font-size:12px;line-height:1.5;color:var(--dim);margin:0}.ml-copy h2{max-width:9ch}.ml-checks{display:grid;gap:13px;margin-top:26px}.ml-check{display:grid;grid-template-columns:25px 1fr;gap:10px;color:var(--dim);font-size:13.5px;line-height:1.55}.ml-check i{width:23px;height:23px;border-radius:50%;background:rgba(88,121,71,.10);color:var(--laurel);display:grid;place-items:center;font-style:normal;font-size:11px}
.ml-cta{padding:92px 0 104px}.ml-ctabox{border:1px solid var(--line);border-radius:24px;background:rgba(255,255,255,.72);padding:60px;display:grid;grid-template-columns:1fr auto;gap:30px;align-items:center;box-shadow:0 24px 64px rgba(29,27,22,.04)}.ml-ctabox h2{font:400 52px/1 var(--didot);margin:0}.ml-ctabox p{color:var(--dim);font-size:14px;line-height:1.6;max-width:54ch;margin:12px 0 0}.ml-ctabox .ml-primary{min-width:150px}
@media(max-width:900px){.ml-hero{grid-template-columns:1fr;min-height:auto;padding:62px 0}.ml-preview{min-height:480px}.ml-sectionhead,.ml-report{grid-template-columns:1fr}.ml-grid3{grid-template-columns:1fr}.ml-feature{border-right:0;border-bottom:1px solid var(--line);min-height:auto}.ml-feature:last-child{border-bottom:0}.ml-ctabox{grid-template-columns:1fr}.ml-ctabox .ml-primary{width:max-content}}
@media(max-width:600px){.ml-wrap{width:min(100% - 30px,1180px)}.ml-hero{padding:46px 0 58px;gap:24px}.ml h1{font-size:54px}.ml-lede{font-size:15px}.ml-actions{align-items:stretch;flex-direction:column}.ml-primary,.ml-secondary{width:100%}.ml-preview{min-height:390px}.ml-orbit{width:330px;height:330px}.ml-card{border-radius:16px}.ml-float{display:none}.ml-section{padding:70px 0}.ml-section h2{font-size:43px}.ml-sectionhead{gap:16px;margin-bottom:28px}.ml-row{grid-template-columns:1fr 54px;gap:7px 12px}.ml-row p{grid-column:1/-1}.ml-ctabox{padding:32px 24px}.ml-ctabox h2{font-size:42px}}
`

const wave=[30,44,58,37,72,46,64,88,40,56,74,42,90,62,49,76,35,67,82,50,68,42,59,73,38,64,49,78,45,61]

export default function MarketingLanding(){
 return <div className="ml"><style>{CSS}</style><PublicNav/>
  <div className="ml-wrap"><section className="ml-hero">
   <div><div className="ml-kicker">AI speaking coach · built for real practice</div><h1>Speak so they <em>listen.</em></h1><p className="ml-lede">Practice interviews, meetings, presentations and everyday conversations. Peitho listens to how you speak, measures what changed, and gives you evidence-backed coaching for the next attempt.</p><div className="ml-actions"><a className="ml-primary" href="/auth/signup">Start practicing</a><a className="ml-secondary" href="#how">See how Peitho works ↓</a></div></div>
   <div className="ml-preview"><div className="ml-orbit"/><div className="ml-card"><div className="ml-cardtop"><span className="ml-cardtitle">Live speaking session</span><span className="ml-live">listening</span></div><div className="ml-wave">{wave.map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><div className="ml-caption">“The main challenge was <mark>um</mark> getting everyone aligned on the same outcome.”</div><div className="ml-stats"><div className="ml-stat"><b>132</b><span>words / min</span></div><div className="ml-stat"><b>4.2</b><span>fillers / min</span></div><div className="ml-stat"><b>0</b><span>long pauses</span></div></div></div><div className="ml-float one"><b>82</b><span>voice performance</span></div><div className="ml-float two"><b>↑ 18%</b><span>filler control</span></div></div>
  </section></div>

  <section className="ml-band" id="how"><div className="ml-wrap ml-section"><div className="ml-sectionhead"><div><div className="ml-eyebrow">How Peitho works</div><h2>Practice. Measure. Improve.</h2></div><p>Peitho combines the things you can count with the things you can hear: pace, fillers, pauses, structure, language quality, vocal clarity, tonal variation and enunciation.</p></div><div className="ml-grid3">
   <article className="ml-feature"><div className="ml-icon">01</div><h3>Speak for real</h3><p>Choose a realistic prompt and answer out loud. Live captions and speaking signals keep you aware without interrupting the flow.</p></article>
   <article className="ml-feature"><div className="ml-icon">02</div><h3>See the evidence</h3><p>Peitho turns the recording into measurable speaking signals and quotes the exact phrases behind its coaching.</p></article>
   <article className="ml-feature"><div className="ml-icon">03</div><h3>Make the next attempt better</h3><p>Every session ends with a focused target, three concrete fixes and a saved review you can revisit from your progress history.</p></article>
  </div></div></section>

  <section id="insights"><div className="ml-wrap ml-section"><div className="ml-report">
   <div className="ml-reportcard"><div className="ml-reporthead"><span>Voice performance report</span><b>78</b></div>{[['Pacing','86','Comfortable conversational range with room around key points.'],['Filler control','72','A few repeated fillers soften otherwise clear transitions.'],['Tonal variation','76','Good variation overall; important claims could carry more emphasis.'],['Enunciation','83','Most words are distinct and easy to follow.']].map(([a,b,d])=><div className="ml-row" key={a}><strong>{a}</strong><b>{b}</b><p>{d}</p></div>)}</div>
   <div className="ml-copy"><div className="ml-eyebrow">A report you can use</div><h2>More than a score.</h2><p className="ml-lede">Peitho separates language quality from voice performance so you can see whether the issue is what you said, how you structured it, or how the delivery landed.</p><div className="ml-checks"><div className="ml-check"><i>✓</i><span>Exact filler and pacing signals from the session.</span></div><div className="ml-check"><i>✓</i><span>Voice performance across tonal variation, projection and enunciation.</span></div><div className="ml-check"><i>✓</i><span>Misheard or unclear moments flagged conservatively instead of treated as grammar mistakes.</span></div></div></div>
  </div></div></section>

  <section className="ml-band" id="progress"><div className="ml-wrap ml-section"><div className="ml-sectionhead"><div><div className="ml-eyebrow">Progress that compounds</div><h2>Your history becomes the coach.</h2></div><p>Completed reviews are saved to your account. Over time, Peitho shows whether your filler pressure, pace, structure and overall session scores are actually moving in the right direction.</p></div><div className="ml-grid3"><article className="ml-feature"><div className="ml-icon">↗</div><h3>Track trends</h3><p>See recent score direction, filler-rate movement and category changes instead of treating every practice as an isolated attempt.</p></article><article className="ml-feature"><div className="ml-icon">◎</div><h3>Reopen any review</h3><p>Go back to the complete result — transcript, voice report, exact fixes and coaching — from your saved session history.</p></article><article className="ml-feature"><div className="ml-icon">★</div><h3>Stay consistent</h3><p>Practice streaks and a weekly leaderboard add just enough pressure to keep the habit moving without rewarding one lucky session.</p></article></div></div></section>

  <div className="ml-wrap ml-cta"><div className="ml-ctabox"><div><h2>Your next answer starts here.</h2><p>Pick a prompt, speak naturally, and let Peitho turn the recording into something you can actually improve.</p></div><a className="ml-primary" href="/auth/signup">Get started</a></div></div>
  <CreatorSignature/>
 </div>
}
