import React from 'react'
const CSS=`@import url('https://fonts.googleapis.com/css2?family=GFS+Didot&family=Instrument+Sans:wght@400;500;600&display=swap');.pv{min-height:100vh;background:#F6F4EF;color:#1D1B16;font-family:'Instrument Sans',sans-serif}.pv *{box-sizing:border-box}.pv-wrap{max-width:820px;margin:0 auto;padding:0 28px 72px}.pv-head{height:82px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #E1DDD0}.pv-brand{font:30px 'GFS Didot',serif;color:#1D1B16;text-decoration:none}.pv-back,.pv a{color:#1A56A8;text-decoration:none}.pv-main{padding-top:56px}.pv-kicker{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#1A56A8;font-weight:600}.pv h1{font:400 clamp(42px,7vw,62px)/1.05 'GFS Didot',serif;margin:11px 0}.pv-updated{font-size:12px;color:#98937F;margin-bottom:32px}.pv-intro{font-size:17px;color:#5F5B4F;line-height:1.75;border-bottom:1px solid #E1DDD0;padding-bottom:28px}.pv section{margin-top:30px}.pv h2{font:400 27px 'GFS Didot',serif;margin:0 0 9px}.pv p,.pv li{font-size:14px;line-height:1.75;color:#5F5B4F}.pv ul{padding-left:20px}.pv-note{background:#fff;border:1px solid #E1DDD0;border-radius:12px;padding:17px 19px;margin-top:34px}.pv-footer{border-top:1px solid #E1DDD0;margin-top:44px;padding-top:20px;font-size:12px;color:#98937F}@media(max-width:600px){.pv-wrap{padding:0 18px 50px}.pv-head{height:68px}.pv-main{padding-top:38px}.pv h1{font-size:44px}.pv-intro{font-size:15px}}`
export default function PrivacyPage(){return <div className="pv"><style>{CSS}</style><div className="pv-wrap"><header className="pv-head"><a className="pv-brand" href="/">Peitho</a><a className="pv-back" href="/">Back to Peitho</a></header><main className="pv-main"><div className="pv-kicker">Your data, in plain language</div><h1>Privacy Policy</h1><div className="pv-updated">Last updated 18 September 2026</div><p className="pv-intro">Peitho is a speaking-practice product built by Satnam Singh. This page explains what Peitho handles when you create an account and practise, without making you read an infrastructure diagram.</p>
<section><h2>1. Your account</h2><p>When you create an account, Peitho stores the information needed to identify your account and personalise practice, such as your name, email address, speaking goal and self-reported level. If you choose Google sign-in, the basic account information you approve is used to sign you in.</p></section>
<section><h2>2. Your microphone and practice sessions</h2><p>Microphone access begins only after you press Start speaking. While you practise, short pieces of audio may be processed to give you the live caption and filler preview. When you end the session, the completed recording is processed to create your final transcript, speaking metrics and coaching.</p><p>The live preview is intentionally fast and can occasionally hear a word incorrectly. The completed session receives a deeper review. Where the audio gives enough evidence, Peitho may also point out a phrase that was difficult to understand, sounded mumbled, or appears to have been misheard by speech recognition. It avoids treating uncertain recognition or accent differences as pronunciation errors.</p></section>
<section><h2>3. What gets saved</h2><p>To make My progress work, Peitho saves your completed session results: the topic, transcript, session length, measurable speaking metrics, scores and coaching feedback. This lets you return later and see how your speaking changes across practice sessions.</p><p>Peitho does not intentionally save your raw microphone recording in its own application database after the review is complete.</p></section>
<section><h2>4. Outside processing</h2><p>Peitho relies on specialist services for account sign-in, speech recognition, AI-assisted coaching, hosting and secure data storage. During a session, the minimum information needed to provide those features may be processed by those services. They handle that information under their own service terms and privacy commitments.</p></section>
<section><h2>5. Why Peitho uses this information</h2><ul><li>to sign you in and keep your account working;</li><li>to create live captions, final transcripts and speaking metrics;</li><li>to generate evidence-based coaching from what you actually said;</li><li>to save your practice history and show progress over time;</li><li>to protect the service from abuse and keep it reliable.</li></ul></section>
<section><h2>6. Automated feedback</h2><p>Speech recognition and AI-generated coaching can make mistakes. Scores describe observable patterns in a practice recording; they are not a measure of your intelligence, personality, employability or worth. A clarity or pronunciation flag is coaching evidence, not a diagnosis, and may still be wrong. Important decisions should not be made from a Peitho score alone.</p></section>
<section><h2>7. Sharing and sale</h2><p>Peitho does not sell your personal information. Information is shared only where needed to operate the features above, protect the service, or comply with applicable law.</p></section>
<section><h2>8. Your choices</h2><p>You decide when microphone access begins and can revoke microphone permission in your browser. You can sign out at any time. Signed-in users can open <a href="/account">Account & data</a> to clear saved practice history or permanently delete their Peitho account and associated saved data. For other questions or corrections, contact Satnam through the portfolio link below.</p></section>
<section><h2>9. Security and sensitive information</h2><p>Peitho uses authenticated accounts, access controls and encrypted web connections. No online service can promise absolute security, so do not use a practice recording to share passwords, financial credentials, medical records or other highly sensitive information.</p></section>
<section><h2>10. Changes</h2><p>If Peitho materially changes what it stores or how practice data is used, this page will be updated and the date above will change.</p></section>
<div className="pv-note"><strong>Questions or data requests</strong><p>Peitho is built by Satnam Singh. Contact details are available at <a href="https://satnamsingh.in" target="_blank" rel="noopener noreferrer">satnamsingh.in</a>.</p></div></main></div></div>}