import React, { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase.client'

const CSS=`
@import url('https://fonts.googleapis.com/css2?family=GFS+Didot&family=Instrument+Sans:wght@400;500;600&display=swap');
.ph{min-height:100vh;background:#F6F4EF;color:#1D1B16;font-family:'Instrument Sans',sans-serif}.ph *{box-sizing:border-box}.ph-wrap{max-width:940px;margin:0 auto;padding:28px 28px 70px}.ph-nav{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #E1DDD0;padding-bottom:20px}.ph-logo{font:28px 'GFS Didot',serif}.ph-nav a{color:#1A56A8;text-decoration:none;font-size:13px}.ph-head{padding:52px 0 28px}.ph-head h1{font:42px/1.1 'GFS Didot',serif;margin:0}.ph-head p{color:#6E6A5C;max-width:60ch}.ph-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:24px}.ph-stat,.ph-chart,.ph-insight{background:#fff;border:1px solid #E1DDD0;border-radius:11px}.ph-stat{padding:17px}.ph-stat b{display:block;font-size:26px}.ph-stat span{font-size:12px;color:#98937F}.ph-trends{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:0 0 30px}.ph-chart{padding:18px}.ph-charthead{display:flex;justify-content:space-between;gap:12px;align-items:baseline}.ph-charthead b{font:20px 'GFS Didot',serif;font-weight:400}.ph-charthead span{font-size:11px;color:#98937F}.ph-svg{width:100%;height:120px;display:block;margin-top:12px}.ph-grid{stroke:#E8E4DA;stroke-width:1}.ph-line{fill:none;stroke:#1A56A8;stroke-width:3;stroke-linecap:round;stroke-linejoin:round}.ph-line.fillers{stroke:#C2492B}.ph-dot{fill:#fff;stroke:#1A56A8;stroke-width:2}.ph-dot.fillers{stroke:#C2492B}.ph-insights{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:-12px 0 30px}.ph-insight{padding:15px}.ph-insight strong{display:block;font-size:13px}.ph-insight p{font-size:11.5px;line-height:1.5;color:#6E6A5C;margin:5px 0 0}.ph-up{color:#587947}.ph-down{color:#C2492B}.ph-list{border-top:1px solid #E1DDD0}.ph-row{padding:19px 4px;border-bottom:1px solid #E1DDD0;display:grid;text-decoration:none;color:inherit;transition:background .15s,padding .15s;grid-template-columns:minmax(0,1.6fr) 70px repeat(4,58px);gap:14px;align-items:center}.ph-row:hover{background:#fff;padding-left:10px;padding-right:10px}.ph-topic b{display:block;font:18px 'GFS Didot',serif;font-weight:400}.ph-topic span{font-size:12px;color:#98937F}.ph-score{font-size:22px;font-weight:600;color:#1A56A8}.ph-mini{text-align:center}.ph-mini b{display:block;font-size:14px}.ph-mini span{font-size:10px;color:#98937F;text-transform:uppercase}.ph-empty{background:#fff;border:1px solid #E1DDD0;border-radius:12px;padding:26px;color:#6E6A5C}.ph-loading{padding:100px 0;color:#6E6A5C}.ph-note{font-size:12px;color:#98937F;margin-top:22px}
@media(max-width:700px){.ph-wrap{padding:20px 17px 55px}.ph-head{padding:38px 0 22px}.ph-head h1{font-size:36px}.ph-stats{grid-template-columns:1fr 1fr}.ph-trends{grid-template-columns:1fr}.ph-insights{grid-template-columns:1fr}.ph-row{grid-template-columns:1fr 58px;gap:10px}.ph-score{text-align:right}.ph-mini{display:inline-flex;gap:5px;text-align:left;margin-right:12px}.ph-mini b{font-size:12px}.ph-mini span{font-size:9px}.ph-row>.ph-mini:nth-of-type(2){grid-column:1}.ph-topic{grid-column:1}.ph-svg{height:105px}}
`

type SessionRow={id:string;topic_title:string;duration_sec:number;overall:number;fluency:number;grammar:number;vocabulary:number;coherence:number;wpm:number;fillers_per_min:number;created_at:string}
const n=(v:any)=>Number(v||0)
function Trend({rows,keyName,invert=false}:{rows:SessionRow[];keyName:'overall'|'fillers_per_min';invert?:boolean}){
 const data=[...rows].slice(0,10).reverse(),vals=data.map(r=>n(r[keyName]));if(!vals.length)return null
 const lo=Math.min(...vals),hi=Math.max(...vals),range=Math.max(1,hi-lo),pts=vals.map((v,i)=>{const x=8+(i/Math.max(1,vals.length-1))*284;const y=100-((v-lo)/range)*78;return{x,y,v}})
 const first=vals[0],last=vals[vals.length-1],delta=last-first,good=invert?delta<=0:delta>=0
 return <div className="ph-chart"><div className="ph-charthead"><b>{keyName==='overall'?'Session score':'Filler pressure'}</b><span className={good?'ph-up':'ph-down'}>{delta===0?'steady':`${delta>0?'+':''}${keyName==='overall'?Math.round(delta):delta.toFixed(1)}`}</span></div><svg className="ph-svg" viewBox="0 0 300 112" role="img" aria-label={`${keyName==='overall'?'Session score':'Fillers per minute'} trend`}><line className="ph-grid" x1="8" y1="22" x2="292" y2="22"/><line className="ph-grid" x1="8" y1="61" x2="292" y2="61"/><line className="ph-grid" x1="8" y1="100" x2="292" y2="100"/><polyline className={'ph-line '+(invert?'fillers':'')} points={pts.map(p=>`${p.x},${p.y}`).join(' ')}/>{pts.map((p,i)=><circle key={i} className={'ph-dot '+(invert?'fillers':'')} cx={p.x} cy={p.y} r="3.5"/>)}</svg><div className="ph-charthead"><span>{data.length} recent sessions</span><span>{keyName==='overall'?`latest ${Math.round(last)}`:`latest ${last.toFixed(1)}/min`}</span></div></div>
}

export default function SessionHistory(){
 const[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[rows,setRows]=useState<SessionRow[]>([]),[streak,setStreak]=useState({current:0,best:0})
 useEffect(()=>{(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){setLoading(false);return}setSignedIn(true);const[{data:sessions},{data:streakRow}]=await Promise.all([supabase.from('sessions').select('id,topic_title,duration_sec,overall,fluency,grammar,vocabulary,coherence,wpm,fillers_per_min,created_at').order('created_at',{ascending:false}).limit(20),supabase.from('streaks').select('current,best').eq('user_id',session.user.id).maybeSingle()]);setRows((sessions||[]) as SessionRow[]);if(streakRow)setStreak(streakRow);setLoading(false)})()},[])
 const stats=useMemo(()=>{if(!rows.length)return{average:0,best:0,pace:0};return{average:Math.round(rows.reduce((x,r)=>x+n(r.overall),0)/rows.length),best:Math.max(...rows.map(r=>n(r.overall))),pace:Math.round(rows.slice(0,5).reduce((x,r)=>x+n(r.wpm),0)/Math.min(5,rows.length))}},[rows])
 const insights=useMemo(()=>{if(rows.length<2)return[];const recent=rows.slice(0,Math.min(3,rows.length)),older=rows.slice(Math.min(3,rows.length),Math.min(6,rows.length));const prev=older.length?older:rows.slice(-Math.min(3,rows.length));const avg=(xs:SessionRow[],k:'overall'|'fillers_per_min'|'coherence')=>xs.reduce((a,r)=>a+n(r[k]),0)/Math.max(1,xs.length);const sd=avg(recent,'overall')-avg(prev,'overall'),fd=avg(recent,'fillers_per_min')-avg(prev,'fillers_per_min'),cd=avg(recent,'coherence')-avg(prev,'coherence');return[{t:'Overall direction',v:sd>=1?'Moving up':sd<=-1?'Needs a reset':'Holding steady',p:`Recent sessions are ${Math.abs(sd).toFixed(1)} points ${sd>=0?'above':'below'} the comparison window.`},{t:'Filler control',v:fd<=-.5?'Getting cleaner':fd>=.5?'More verbal clutter':'Stable',p:`Filler pressure changed ${Math.abs(fd).toFixed(1)} per minute.`},{t:'Idea structure',v:cd>=2?'Improving':cd<=-2?'Needs focus':'Consistent',p:`Coherence moved ${Math.abs(cd).toFixed(1)} points across the recent window.`}]},[rows])
 const fmt=(s:number)=>`${Math.floor((s||0)/60)}:${String((s||0)%60).padStart(2,'0')}`
 return <main className="ph"><style>{CSS}</style><div className="ph-wrap">{loading?<div className="ph-loading">Opening your progress…</div>:!signedIn?<><header className="ph-head"><h1>Your progress.</h1></header><div className="ph-empty">Sign in on the Peitho home page to see your speaking history. <a href="/">Go to Peitho →</a></div></>:<><header className="ph-head"><h1>Your progress.</h1><p>Look for direction, not one perfect score. Peitho tracks whether your delivery is becoming clearer and less effortful across sessions.</p></header><section className="ph-stats"><div className="ph-stat"><b>{rows.length}</b><span>recent sessions</span></div><div className="ph-stat"><b>{stats.average||'—'}</b><span>average score</span></div><div className="ph-stat"><b>{stats.best||'—'}</b><span>best score</span></div><div className="ph-stat"><b>{streak.current}</b><span>current streak · best {streak.best}</span></div></section>{rows.length>0&&<><section className="ph-trends"><Trend rows={rows} keyName="overall"/><Trend rows={rows} keyName="fillers_per_min" invert/></section>{insights.length>0&&<section className="ph-insights">{insights.map(x=><div className="ph-insight" key={x.t}><strong>{x.t} · {x.v}</strong><p>{x.p}</p></div>)}</section>}</>}{rows.length===0?<div className="ph-empty">Your first completed practice will appear here. <a href="/">Start a session →</a></div>:<section className="ph-list">{rows.map(r=><a className="ph-row" href={`/history/${r.id}`} key={r.id}><div className="ph-topic"><b>{r.topic_title}</b><span>{new Date(r.created_at).toLocaleDateString()} · {fmt(r.duration_sec)} · {Math.round(n(r.wpm))} WPM · {n(r.fillers_per_min).toFixed(1)} fillers/min · Open review →</span></div><div className="ph-score">{Math.round(n(r.overall))}</div><div className="ph-mini"><b>{Math.round(n(r.fluency))}</b><span>Fluency</span></div><div className="ph-mini"><b>{Math.round(n(r.grammar))}</b><span>Grammar</span></div><div className="ph-mini"><b>{Math.round(n(r.vocabulary))}</b><span>Vocab</span></div><div className="ph-mini"><b>{Math.round(n(r.coherence))}</b><span>Flow</span></div></a>)}</section>}<p className="ph-note">Showing your 20 most recent sessions. Trends describe practice performance, not a fixed measure of ability.</p></>}</div></main>
}
