import React, { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase.client'

const CSS = `
@import url('https://fonts.googleapis.com/css2?family=GFS+Didot&family=Instrument+Sans:wght@400;500;600&display=swap');
.ph{min-height:100vh;background:#F6F4EF;color:#1D1B16;font-family:'Instrument Sans',sans-serif}.ph *{box-sizing:border-box}.ph-wrap{max-width:940px;margin:0 auto;padding:28px 28px 70px}.ph-nav{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #E1DDD0;padding-bottom:20px}.ph-logo{font:28px 'GFS Didot',serif}.ph-nav a{color:#1A56A8;text-decoration:none;font-size:13px}.ph-head{padding:52px 0 28px}.ph-head h1{font:42px/1.1 'GFS Didot',serif;margin:0}.ph-head p{color:#6E6A5C;max-width:58ch}.ph-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:30px}.ph-stat{background:#fff;border:1px solid #E1DDD0;border-radius:11px;padding:17px}.ph-stat b{display:block;font-size:26px}.ph-stat span{font-size:12px;color:#98937F}.ph-list{border-top:1px solid #E1DDD0}.ph-row{padding:19px 4px;border-bottom:1px solid #E1DDD0;display:grid;grid-template-columns:minmax(0,1.6fr) 70px repeat(4,58px);gap:14px;align-items:center}.ph-topic b{display:block;font:18px 'GFS Didot',serif;font-weight:400}.ph-topic span{font-size:12px;color:#98937F}.ph-score{font-size:22px;font-weight:600;color:#1A56A8}.ph-mini{text-align:center}.ph-mini b{display:block;font-size:14px}.ph-mini span{font-size:10px;color:#98937F;text-transform:uppercase}.ph-empty{background:#fff;border:1px solid #E1DDD0;border-radius:12px;padding:26px;color:#6E6A5C}.ph-loading{padding:100px 0;color:#6E6A5C}.ph-note{font-size:12px;color:#98937F;margin-top:22px}
@media(max-width:700px){.ph-wrap{padding:20px 17px 55px}.ph-head{padding:38px 0 22px}.ph-head h1{font-size:36px}.ph-stats{grid-template-columns:1fr 1fr}.ph-row{grid-template-columns:1fr 58px;gap:10px}.ph-score{text-align:right}.ph-mini{display:inline-flex;gap:5px;text-align:left;margin-right:12px}.ph-mini b{font-size:12px}.ph-mini span{font-size:9px}.ph-row>.ph-mini:nth-of-type(2){grid-column:1}.ph-row>.ph-mini{grid-column:auto}.ph-topic{grid-column:1}.ph-row:after{content:''}}
`

type SessionRow = { id:string; topic_title:string; duration_sec:number; overall:number; fluency:number; grammar:number; vocabulary:number; coherence:number; wpm:number; fillers_per_min:number; created_at:string }

export default function SessionHistory(){
  const [loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[rows,setRows]=useState<SessionRow[]>([]),[streak,setStreak]=useState({current:0,best:0})
  useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setLoading(false);return}setSignedIn(true);const [{data:sessions},{data:streakRow}]=await Promise.all([supabase.from('sessions').select('id,topic_title,duration_sec,overall,fluency,grammar,vocabulary,coherence,wpm,fillers_per_min,created_at').order('created_at',{ascending:false}).limit(20),supabase.from('streaks').select('current,best').eq('user_id',session.user.id).maybeSingle()]);setRows((sessions||[]) as SessionRow[]);if(streakRow)setStreak(streakRow);setLoading(false)})()},[])
  const stats=useMemo(()=>{if(!rows.length)return{average:0,best:0};return{average:Math.round(rows.reduce((n,r)=>n+Number(r.overall||0),0)/rows.length),best:Math.max(...rows.map(r=>Number(r.overall||0))) }},[rows])
  const fmt=(s:number)=>`${Math.floor((s||0)/60)}:${String((s||0)%60).padStart(2,'0')}`
  return <main className="ph"><style>{CSS}</style><div className="ph-wrap"><nav className="ph-nav"><div className="ph-logo">Peitho</div><a href="/">← Practice</a></nav>{loading?<div className="ph-loading">Loading your progress…</div>:!signedIn?<><header className="ph-head"><h1>Your progress.</h1></header><div className="ph-empty">Sign in on the Peitho home page to see your speaking history. <a href="/">Go to Peitho →</a></div></>:<><header className="ph-head"><h1>Your progress.</h1><p>Recent practice, saved to your account. Scores are coaching signals, not formal language-test grades.</p></header><section className="ph-stats"><div className="ph-stat"><b>{rows.length}</b><span>recent sessions</span></div><div className="ph-stat"><b>{stats.average || '—'}</b><span>average score</span></div><div className="ph-stat"><b>{stats.best || '—'}</b><span>best score</span></div><div className="ph-stat"><b>{streak.current}</b><span>current streak · best {streak.best}</span></div></section>{rows.length===0?<div className="ph-empty">Your first completed practice will appear here. <a href="/">Start a session →</a></div>:<section className="ph-list">{rows.map(r=><article className="ph-row" key={r.id}><div className="ph-topic"><b>{r.topic_title}</b><span>{new Date(r.created_at).toLocaleDateString()} · {fmt(r.duration_sec)} · {Math.round(Number(r.wpm||0))} WPM · {Number(r.fillers_per_min||0).toFixed(1)} fillers/min</span></div><div className="ph-score">{Math.round(Number(r.overall||0))}</div><div className="ph-mini"><b>{Math.round(Number(r.fluency||0))}</b><span>Fluency</span></div><div className="ph-mini"><b>{Math.round(Number(r.grammar||0))}</b><span>Grammar</span></div><div className="ph-mini"><b>{Math.round(Number(r.vocabulary||0))}</b><span>Vocab</span></div><div className="ph-mini"><b>{Math.round(Number(r.coherence||0))}</b><span>Flow</span></div></article>)}</section>}<p className="ph-note">Showing your 20 most recent sessions.</p></>}</div></main>
}
