import React,{useEffect,useRef,useState} from 'react'
import type{Session}from '@supabase/supabase-js'
import{ supabase }from'../lib/supabase.client'
const CSS=`.pn{position:sticky;top:0;z-index:80;background:rgba(246,244,239,.94);backdrop-filter:blur(12px);border-bottom:1px solid #E1DDD0;font-family:'Instrument Sans',-apple-system,'Segoe UI',sans-serif}.pn *{box-sizing:border-box}.pn-inner{max-width:1180px;margin:0 auto;height:70px;padding:0 28px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:18px}.pn-brand{font:400 27px 'GFS Didot',Georgia,serif;color:#1D1B16;text-decoration:none;display:inline-flex;align-items:center;gap:9px}.pn-mark{width:31px;height:31px;border-radius:8px}.pn-motto{font-size:12px;color:#6E6A5C;letter-spacing:.04em;white-space:nowrap}.pn-actions{display:flex;justify-content:flex-end;align-items:center;gap:7px}.pn-link,.pn-account{border:1px solid transparent;background:transparent;color:#5F5B4F;text-decoration:none;border-radius:999px;padding:8px 11px;font:500 12px 'Instrument Sans',sans-serif;white-space:nowrap}.pn-link:hover,.pn-account:hover{background:#fff;border-color:#E1DDD0;color:#1A56A8}.pn-link.board{background:#fff;border-color:#E1DDD0;color:#1A56A8}.pn-menuwrap{position:relative}.pn-account{cursor:pointer;display:flex;align-items:center;gap:6px}.pn-caret{font-size:9px}.pn-menu{position:absolute;right:0;top:calc(100% + 8px);width:190px;background:#fff;border:1px solid #E1DDD0;border-radius:11px;padding:6px;box-shadow:0 12px 36px rgba(29,27,22,.13)}.pn-menu a,.pn-menu button{display:block;width:100%;border:0;background:none;text-align:left;text-decoration:none;color:#5F5B4F;padding:10px 11px;border-radius:7px;font:500 12px 'Instrument Sans',sans-serif;cursor:pointer}.pn-menu a:hover,.pn-menu button:hover{background:#F6F4EF;color:#1A56A8}.pn-divider{height:1px;background:#EEEAE0;margin:4px 5px}.pg-account{display:none!important}.pu .mast{display:none!important}
@media(max-width:700px){.pn-inner{height:62px;padding:0 16px;grid-template-columns:auto 1fr}.pn-brand{font-size:24px}.pn-mark{width:28px;height:28px}.pn-motto{display:none}.pn-actions{gap:4px}.pn-link,.pn-account{padding:8px 9px;font-size:11px}.pn-menu{position:fixed;right:12px;top:68px;width:min(230px,calc(100vw - 24px))}}
@media(max-width:390px){.pn-inner{padding:0 12px}.pn-brand{font-size:22px;gap:7px}.pn-mark{width:26px;height:26px}.pn-link{padding:7px 8px}.pn-account{max-width:94px;overflow:hidden;text-overflow:ellipsis}}
`
export default function SignedInNav(){
 const[session,setSession]=useState<Session|null>(null),[open,setOpen]=useState(false),wrap=useRef<HTMLDivElement|null>(null)
 useEffect(()=>{if(window.location.hash==='#/'||window.location.hash==='#')history.replaceState(null,'',window.location.pathname+window.location.search);window.scrollTo(0,0);supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));const reset=(event:MouseEvent)=>{const el=event.target as HTMLElement|null;if(el?.closest('.topic-row,.crumb button,.actions button,.start'))setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),25);if(wrap.current&&!wrap.current.contains(el))setOpen(false)};document.addEventListener('click',reset,true);return()=>{sub.subscription.unsubscribe();document.removeEventListener('click',reset,true)}},[])
 if(!session)return null
 const name=String(session.user.user_metadata?.full_name||session.user.user_metadata?.name||session.user.email||'Account').split(' ')[0]
 return <nav className="pn"><style>{CSS}</style><div className="pn-inner"><a className="pn-brand" href="/"><img className="pn-mark" src="/favicon.svg" alt=""/>Peitho</a><div className="pn-motto">Speak · Measure · Improve</div><div className="pn-actions"><a className="pn-link board" href="/leaderboard">Leaderboard</a><div className="pn-menuwrap" ref={wrap}><button className="pn-account" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-haspopup="menu">{name}<span className="pn-caret">▼</span></button>{open&&<div className="pn-menu" role="menu"><a href="/history">My progress</a><a href="/account">Account & data</a><div className="pn-divider"/><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div>}</div></div></div></nav>
}
