import React,{useEffect,useRef,useState}from'react'
import type{Session}from'@supabase/supabase-js'
import{supabase}from'../lib/supabase.client'

const CSS=`
.pn{position:sticky;top:0;z-index:90;padding:16px 22px 0;background:linear-gradient(180deg,rgba(246,244,239,.98) 0%,rgba(246,244,239,.88) 74%,rgba(246,244,239,0) 100%);font-family:'Instrument Sans',-apple-system,'Segoe UI',sans-serif}.pn *{box-sizing:border-box}.pn-inner{width:min(1180px,100%);height:66px;margin:0 auto;padding:0 14px 0 13px;background:rgba(255,255,255,.78);border:1px solid rgba(225,221,208,.95);border-radius:999px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:18px;box-shadow:0 10px 34px rgba(29,27,22,.045);backdrop-filter:blur(16px)}.pn-brand{font:400 27px 'GFS Didot',Georgia,serif;color:#1D1B16;text-decoration:none;display:inline-flex;align-items:center;gap:9px;width:max-content}.pn-mark{width:32px;height:32px;border-radius:9px}.pn-motto{font-size:12px;color:#6E6A5C;letter-spacing:.04em;white-space:nowrap}.pn-actions{display:flex;justify-content:flex-end;align-items:center;gap:7px}.pn-link,.pn-account{border:1px solid transparent;background:transparent;color:#5F5B4F;text-decoration:none;border-radius:10px;padding:9px 12px;font:500 12px 'Instrument Sans',sans-serif;white-space:nowrap}.pn-link:hover,.pn-account:hover{background:#F6F4EF;border-color:#E1DDD0;color:#1A56A8}.pn-link.board{background:#1A56A8;border-color:#1A56A8;color:#fff}.pn-link.board:hover{background:#123E7C}.pn-menuwrap{position:relative}.pn-account{cursor:pointer;display:flex;align-items:center;gap:7px}.pn-avatar{width:22px;height:22px;border-radius:50%;display:grid;place-items:center;background:rgba(26,86,168,.09);color:#1A56A8;font-size:10px;font-weight:700}.pn-caret{font-size:8px}.pn-menu{position:absolute;right:0;top:calc(100% + 9px);width:205px;background:#fff;border:1px solid #E1DDD0;border-radius:12px;padding:7px;box-shadow:0 18px 44px rgba(29,27,22,.13)}.pn-menu a,.pn-menu button{display:block;width:100%;border:0;background:none;text-align:left;text-decoration:none;color:#5F5B4F;padding:10px 11px;border-radius:8px;font:500 12px 'Instrument Sans',sans-serif;cursor:pointer}.pn-menu a:hover,.pn-menu button:hover{background:#F6F4EF;color:#1A56A8}.pn-divider{height:1px;background:#EEEAE0;margin:4px 5px}.pg-account{display:none!important}.pu .mast{display:none!important}
@media(max-width:700px){.pn{padding:10px 10px 0}.pn-inner{height:58px;padding:0 9px 0 10px;grid-template-columns:auto 1fr}.pn-brand{font-size:23px}.pn-mark{width:29px;height:29px}.pn-motto{display:none}.pn-actions{gap:4px}.pn-link,.pn-account{padding:8px 9px;font-size:11px}.pn-account>span:not(.pn-avatar):not(.pn-caret){display:none}.pn-menu{position:fixed;right:12px;top:76px;width:min(230px,calc(100vw - 24px))}}
`

export default function SignedInNav(){
 const[session,setSession]=useState<Session|null>(null),[open,setOpen]=useState(false),wrap=useRef<HTMLDivElement|null>(null)
 useEffect(()=>{if(window.location.hash==='#/'||window.location.hash==='#')history.replaceState(null,'',window.location.pathname+window.location.search);window.scrollTo(0,0);supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));const reset=(event:MouseEvent)=>{const el=event.target as HTMLElement|null;if(el?.closest('.topic-row,.crumb button,.actions button,.start'))setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),25);if(wrap.current&&!wrap.current.contains(el))setOpen(false)};document.addEventListener('click',reset,true);return()=>{sub.subscription.unsubscribe();document.removeEventListener('click',reset,true)}},[])
 if(!session)return null
 const full=String(session.user.user_metadata?.full_name||session.user.user_metadata?.name||session.user.email||'Account')
 const name=full.split(' ')[0],initial=name.slice(0,1).toUpperCase()
 return <nav className="pn"><style>{CSS}</style><div className="pn-inner"><a className="pn-brand" href="/"><img className="pn-mark" src="/favicon.svg" alt=""/>Peitho</a><div className="pn-motto">Speak · Measure · Improve</div><div className="pn-actions"><a className="pn-link board" href="/leaderboard">Leaderboard</a><div className="pn-menuwrap" ref={wrap}><button className="pn-account" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-haspopup="menu"><span className="pn-avatar">{initial}</span><span>{name}</span><span className="pn-caret">▼</span></button>{open&&<div className="pn-menu" role="menu"><a href="/">Practice</a><a href="/history">My progress</a><a href="/account">Account & data</a><div className="pn-divider"/><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div>}</div></div></div></nav>
}
